on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    container: akashisn/latexmk:full
    name: Compile PDF with Tags
    steps:
      - name: Get Current Time
        uses: 1466587594/get-current-time@v2
        id: current_time
        with:
          format: "YYYY-MM-DD"
          utcOffset: "+09:00"
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile Tex File
        run: mkdir -p out && latexmk -pdfdvi main.tex
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.current_time.outputs.formattedTime}}
          release_name: Release ${{steps.current_time.outputs.formattedTime}}
          body: |
            Compiled PDF Weekly ${{steps.current_time.outputs.formattedTime}}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
      - name: Upload
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: ./out/main.pdf